### ISSUE TITLE
SDL_Main.fs

### ISSUE THREAD

**Issue by averycoolbean** [JeremiahCheatham/Gforth-SDL2-Bindings#1]
good morning!

first tried to use these bindings a few weeks back but have so far been unable to quite get them working. when importing SDL.fs in my forth program all the files up until SDL_main.fs work fine but upon requiring SDL_main.fs gforth presents me with the following error:

```
file not found
in file included from *OS command line*:-1
in file included from src/start.fs:1
in file included from dep/Gforth-SDL2-Bindings/SDL2/SDL.fs:6
dep/Gforth-SDL2-Bindings/SDL2/SDL_main.fs:11: open-lib failed
>>>end-c-library<<<
Backtrace:
$7FB5BCA7F988 throw
$7FB5BCABBD90 c(abort")
$7FB5BCABC640 compile-wrapper-function1
```

i tried to look into this issue myself and was able to find compile-wrapper-function1 in libcc.fs from the gforth source code but don't have a good enough understanding of the broader c-interface code to actually diagnose the issue. also took a look at the SDL_main.h header file but gave up on pursuing that route due to simply not knowing c well enough to understand anything going on in there

im on debian 12 using gforth 0.7.3, sdl 2.26.5, gcc 12.2 and libtool 2.4.7 (i think that should be all the relevant software versions. if not feel free to ask but also it should just be the version in the debian 12 repos)

haven't yet sanity checked the install by trying to run the code on a separate machine, gonna try to do that next but writing this issue first cause ive already been putting this off for like 2 weeks so if i don't finish it now odds are i will continue to procrastinate beyond the heat death of the universe

**Comment by averycoolbean** [comment]
no issues of any kind on openbsd 7.6... why is debian always like this

feel free to just close this as "cant reproduce" or whatever if you cant think of anything either

**Comment by averycoolbean** [comment]
ok after a friend who is a bit more knowledgeable on compilers and linkers also encountered this issue on gentoo they checked with strace

gforth opens `~/.gforth/libcc-named/.libs/sdl_main.so.0` mmaps 1640 bytes of memory, uses mmap again to change the protections for parts of it and then just stops, closes the file, munmap's the memory it was using and tries to open `~/.gforth/libcc-named/sdl_main.so.0` which doesnt exist then restarts the entire process with sdl_main.c (until it does this again and writes the error)

note that where it stops and calls munmap, successful runs like sdl_stdinc.so instead call mprotect on their working memory, read what looks like forth code, close the file and move on

gforth generates sdl_main.so just fine with no visible compiler or linker errors, but fails to actually use it on certain machines and i havent got the faintest fucking clue why. amazing

ill try objdump-ing sdl_main.o next i guess but at this point im way beyond what i understand again

**Comment by averycoolbean** [comment]
note that debian didnt fuck up the packaging so libcc.h is where its supposed to be, havent tried just using gforth 0.7.9 yet but apparently that helped for some people

**Comment by averycoolbean** [comment]
after far too much time trying to understand the code and how to use dbg: apparently the error code is in fact incredibly accurate

open-lib fails. the forth code runs literally identically all the way right up until open-lib, yet open-lib fails for sdl_main and sdl_video and none of the other bindings. open-lib just fails for these 2 files for no apparent reason (as far as i can tell the open-lib primitive just calls gforth_dlopen() which also doesnt do anything unusual (runs either libtool's wrapper around dlopen(), the system dlopen() or the win32 equivalent just based on #ifdef shenanigans)

so yea, this probably deserves being escalated to upstream gforth since its 100% doesnt look to be a problem with ur bindings (though im still not entirely on board with *not* blaming debian since something still needs to trigger whatever horrendous bug this is)

**Comment by JeremiahCheatham** [comment]
Hello. This is the old repo although the issue you are having is probably not fixed with the new one. I would have to get a debian system up and running but my guess is you are missing some build tools or required header files. When gforth first tries to run it actually has a c compiler to build the c libraries. But it's not very helpful when or how it fails. But you should check the bug reports here. And it has an OS license on it.

https://github.com/ProgrammingRainbow/Beginners-Guide-to-SDL2-in-Gforth/

https://youtube.com/playlist?list=PLO02jwa2ZaiAi1DOLTBJloy1mj-Zm5K1s&si=UVsmdx5R_53BddqB

**Comment by averycoolbean** [comment]
fair enough i can create an issue on that repo if ya want but also at this point im pretty confident the issue isnt even relevant to the bindings but rather a bug with either gforth itself misbehaving under specific circumstances or the specific packages being faulty since, as ive pointed out, the only thing that differs between a binding that was generated, compiled, linked and opened successfully and one that failed is wether open-lib succeeded or not
![image](https://github.com/user-attachments/assets/3732a3c3-6af7-4996-adee-975a790243ae)

**Comment by averycoolbean** [comment]
literally right after that i tried compiling gforth from source because i took note of the aur package overriding the default cflags to be just `-std=gnu99` (something i avoided so far because compiling from source is generally a pain in the ass on debian)

compiled from source gforth works (i can even do -O2 to make it a bit faster than the arch build), when my gentoo friend compiles it with -O1 it works but -O2 breaks it. apparently open-lib is just EXTREMELY sensitive to how it was compiled which is extremely interesting behaviour from code that essentially just wraps dlopen()

could be a ltdlopen or glibc dlopen issue but im definitely out of my depth on that. either way i was right and the software was wrong and thats all that matters now (oh and ya know, running gforth compiled from source works so i can actually use the bindings now, thats pretty nice too)
